# Generated by Django 5.2.6 on 2025-09-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemeal',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
