# Generated by Django 5.1.6 on 2025-09-05 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipemeal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemeal',
            name='content',
            field=models.TextField(default='content', max_length=250, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
