# Generated by Django 5.1.6 on 2025-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipemeal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemeal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
