# Generated by Django 5.1.6 on 2025-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipemeal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemeal',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
