# Generated by Django 5.2.6 on 2025-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipemeal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemeal',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
